### ISSUE TITLE
can't handle playlists of 101 or more songs well

### ISSUE THREAD

**Issue by sakuraimikoto33** [zacharyeller13/spotipylist#32]
try to convert a playlist of 101 or more songs, only 100 songs will be added to the playlist.
I used google translate

**Comment by zacharyeller13** [comment]
@sakuraimikoto33, thank you for bringing this to my attention.

Looks like this is because Spotify's API returns paginated results with no more than 100 tracks at a time.  I didn't account for this so currently it only pulls the first 100 tracks and then ends.  I'll fix this for the next release
